name: Increment Version on Merge
on:
  workflow_call:
    inputs:
      default-branch:
        description: Default branch of which contains the tag
        required: false
        type: string
        default: main
jobs:
  version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == inputs.default-branch

    runs-on: ubuntu-latest

    steps:
      # Generally speaking, when the PR contents are treated as passive data, i.e. not in a
      # position  of influence over the build/testing process, it is safe to checkout the code
      # on a pull_request_target (which most of the builds using this reusable workflow use).  
      # In this case it should be fine because changes will have been reviewed before this 
      # workflow is triggered, and we are checking out the default branch.
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.default-branch }}
          fetch-depth: 0

      # See https://github.com/im-open/git-version-lite for more details around how to increment
      # major/minor/patch through commit messages
      - name: Increment the version
        uses: im-open/git-version-lite@v2
        id: version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          default-release-type: major

      - name: Create version tag, create or update major, and minor tags
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.version.outputs.NEXT_VERSION }} ${{ github.sha }}
          git tag -f ${{ steps.version.outputs.NEXT_MAJOR_VERSION }} ${{ github.sha }}
          git tag -f ${{ steps.version.outputs.NEXT_MINOR_VERSION }} ${{ github.sha }}
          git push origin ${{ steps.version.outputs.NEXT_VERSION }}
          git push origin ${{ steps.version.outputs.NEXT_MAJOR_VERSION }} -f
          git push origin ${{ steps.version.outputs.NEXT_MINOR_VERSION }} -f
